module.exports = [
  {
    fileName: 'popcorn.html',
    thumbnail: './img/popcorn/popcorn-thumbnail.jpg',
    images: [
      './img/popcorn/popcorn-1.jpg',
      './img/popcorn/popcorn-2.jpg',
    ],
    title: 'ポップコーン販売（外ブース）',
    text: [
      '塩味とキャラメル味の二種類を販売しています．',
      'ぜひ買っていってくださいね！',
    ],
  },
  {
    fileName: 'web.html',
    thumbnail: './img/web/web-thumbnail.png',
    images: [
      './img/web/web-1.png',
      './img/web/web-2.png',
      './img/web/web-3.png',
    ],
    title: '理大祭特設サイト',
    text: [
      '理大祭の特設サイトも一から作っています．',
    ],
  },
  {
    fileName: 'SLG.html',
    thumbnail: './img/SLG/SLG-thumbnail.png',
    images: [
      './img/SLG/SLG-1.png',
      './img/SLG/SLG-2.png',
      './img/SLG/SLG-3.png',
      './img/SLG/SLG-4.png',
    ],
    title: 'SLG',
    text: [
      'ターン制のシミュレーションゲームです． 比較的難易度は高めになっています．',
      '',
      '情報科学科二年の情報科学演習で作成しました．Javaで実装されています．',
      'システム制作で力尽きたため，ステージ自体はシンプルでバランス調整もままならない状況になっています．一応ちゃんとした手順を踏めばクリアは可能です．半ばパズルゲームのようになっていますね．',
      '操作方法は画面の下の方に全て書かれています．',
    ],
  },
  {
    fileName: 'mioroshi.html',
    thumbnail: './img/mioroshi/mioroshi-thumbnail.png',
    images: [
      './img/mioroshi/mioroshi-1.png',
      './img/mioroshi/mioroshi-2.png',
    ],
    title: '見下ろし型アクションゲーム',
    text: [
      '見下ろし型アクションゲームです．',
      '敵をすべて倒せばクリアとなります．',
      '',
      '矢印キーで移動，zキーで攻撃ができます．',
      '敵に触るとダメージを受けます．',
    ],
  },
  {
    fileName: 'udhita.html',
    thumbnail: './img/udhita/udhita-thumbnail.png',
    images: [
      './img/udhita/udhita-1.png',
    ],
    title: '対にわとりアクションゲーム',
    text: [
      'ただひたすらたくさんのニワトリを倒す無双ゲーです。',
      '操作方法は十字キーで移動、zキーで攻撃です。',
      'クリア後にクリアまでどれだけ時間がかかったかを表示します。',
    ],
  },
  {
    fileName: 'torigautsu.html',
    thumbnail: './img/torigautsu/torigautsu-thumbnail.png',
    images: [
      './img/torigautsu/torigautsu-1.png',
      './img/torigautsu/torigautsu-2.png',
    ],
    title: 'チキンシューティング',
    text: [
      '鳥が撃つ',
      '',
      'キーボード：',
      '方向キー：カーソル・プレイヤー移動',
      'Zキー：決定・攻撃停止',
      'Xキー：キャンセル・ポーズ',
      'Q、Wキー：武器切り替え',
      '',
      'マウス：',
      '左クリック：選択肢を選択・プレイヤー移動',
      '右クリック：キャンセル・ポーズ',
      'ホイール上下：武器切り替え',
      '',
      '本体：https://1drv.ms/u/s!ApII0f54SxFqhwkpJKl31I3A0V3p',
    ],
  },
  {
    fileName: 'welsian.html',
    thumbnail: './img/welsian/welsian-thumbnail.png',
    images: [
      './img/welsian/welsian-1.png',
      './img/welsian/welsian-2.png',
    ],
    title: 'ウエルシアン',
    text: [
      '薬をうってうってうちまくれ！',
      '',
      '操作方法',
      '左右矢印キーで移動、Zキーで弾を撃つ',
    ],
  },
  {
    fileName: 'iraira.html',
    thumbnail: './img/iraira/iraira-thumbnail.png',
    images: [
      './img/iraira/iraira-1.png',
      './img/iraira/iraira-2.png',
    ],
    title: 'iraira',
    text: [
      '要するにイライラ棒。',
      'マウスで操作。',
      '',
      'https://drive.google.com/drive/folders/0Bz5LefCdnSThc3d3WHc3Tkx5VnM?usp=sharing',
    ],
  },
  {
    fileName: 'ImgDw.html',
    thumbnail: './img/ImgDw/ImgDw-thumbnail.png',
    images: [
      './img/ImgDw/ImgDw-1.png',
      './img/ImgDw/ImgDw-2.png',
    ],
    title: 'ImgDw',
    text: [
      'やりたかったこと',
      'Bingの画像検索にはセーフサーチがある。',
      'セーフサーチがかかっているとアレな画像が表示されない。',
      '一方セーフサーチを切ると普通の画像とアレな画像が両方表示される。',
      'つまりセーフサーチ切の結果からセーフサーチ入の結果を抜けばアレな画像だけが抽出できるのでは・・・？！。',
      '',
      '使い方',
      '上の長いテキストボックスに検索ワードを入力して実行を押せば画像が保存される。',
      '検索オプションのセーフサーチで上の話をやる。',
      'なおバグだらけでうまくいかない模様。',
    ],
  },
];
